name: 🚀 Deploy to Azure (Daily Schedule)

on:
  push:
    branches: [main]
  schedule:
  - cron: '31 1 * * *'  # รันทุกวันเวลา 08:31 (เวลาไทย)

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: .
        registryUrl: myexchangeacr.azurecr.io
        registryUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        registryPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        containerAppName: exchange-rate-bot
        resourceGroup: my-first-docker-rg
        containerAppEnvironment: exchange-rate-bot-env
        location: westus2
