name: 🚀 Trigger Bot HTTP Endpoint

on:
  schedule:
    - cron: '31 1 * * *'   # เวลาไทย 08:31 (UTC+7)
  workflow_dispatch:        # กดรันเองได้

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger bot endpoint
        run: |
          curl -s -X GET https://exchange-rate-bot--0000010.bravegrass-436d065b.westus2.azurecontainerapps.io/run
